# default_comments.py

DEFAULT_COMMENTS = [
    """Loving this! 🔥""",
    """This made my day! 😄""",
    """Couldn't agree more! 👏""",
    """Wow, just wow! 😍""",
    """This is amazing! 😎""",
    """Pure gold! 💯""",
    """Such a mood! 😂""",
    """So true! 🙌""",
    """Nailed it! 💥""",
    """This is everything! ❤️""",
    """Incredible work! 👌""",
    """Too good! 😆""",
    """Absolutely love this! 😍""",
    """Mind-blowing! 🤯""",
    """This is awesome! 🤩""",
    """So well said! 💬""",
    """Totally relatable! 🙈""",
    """Such great content! 👍""",
    """This just made my day! 🌟""",
    """On point! 🎯""",
    """Well done! 👏""",
    """This is next level! 🚀""",
    """Keep up the great work! 💪""",
    """So inspirational! 🌟""",
    """Just perfect! ✨""",
    """Just stumbled upon this and had to share! 🤩""",
    """This totally made my day. Thanks for sharing! 😄""",
    """Can’t stop laughing at this! 😂😂""",
    """Exactly what I needed to see today. 🙌""",
    """This is pure genius! 👏""",
    """I can’t believe how much I relate to this. 😅""",
    """This hit me right in the feels. ❤️""",
    """Literally couldn’t agree more with this! 💯""",
    """This is everything I didn’t know I needed today. 😍""",
    """Such a vibe! Love this so much. ✨""",
    """This is the kind of content I’m here for! 🙌""",
    """Wow, this just blew my mind. 🤯""",
    """Yup, this is me all the way! 😆""",
    """This is gold! Thanks for posting it. 🙏""",
    """I’m obsessed with this. Need more of it in my life! 😍""",
    """Just when I thought today couldn’t get better... this pops up! 😁""",
    """The accuracy here is unreal! 😂""",
    """How is this so perfect? Seriously! 👌""",
    """This is definitely going on my mood board. 🎯""",
    """You just won the internet with this one! 🏆""",
    """This made me smile so much. 😊""",
    """I needed a good laugh today, and this delivered! 😂""",
    """This is too good not to share. 😍""",
    """Can we just take a moment to appreciate how awesome this is? 🙌""",
    """So glad I saw this today. Made my whole day better! 🌟""",
    """Trying not to violate community guidelines with how hard I’m laughing at this! 😂""",
    """This is so good, it should come with a community guidelines warning! 😜""",
    """If laughing at this breaks the community guidelines, then I’m guilty as charged! 😆""",
    """I promise this comment doesn’t violate any community guidelines... probably. 🤞""",
    """This might be dangerously funny, but I swear it’s still community guidelines friendly! 😂""",
    """If loving this is wrong, then the community guidelines need to be rewritten! 😂""",
    """Don’t worry, this laugh is 100% community guidelines approved! 😂""",
    """Too funny, but definitely not crossing any community guidelines lines! 😎""",
    """Can’t believe this isn’t flagged for being too hilarious! 😂 #SafeForWork""",
    """This is everything! Double tap if you agree! ❤️""",
    """If you’re not loving this, you’re doing Instagram wrong. 👍""",
    """Stop scrolling and hit that like button if this made you smile! 😊💯""",
    """Just dropped a like because this post deserves it! 💥""",
    """This is what peak content looks like. Like if you agree! 💯🔥""",
    """Can we just appreciate how awesome this is? Double tap! 🙌❤️""",
    """This is too good not to like! 😍💯""",
    """If this doesn’t get all the likes, I don’t know what will! ❤️💥""",
    """I’m just here to give this post the like it deserves! 👍🔥""",
    """Like this if it made your day just a little bit better! 😊❤️""",
]
