# default_comments.py

DEFAULT_COMMENTS = [
    """This is awesome, thanks for sharing!""",
    """Seriously made my day better!""",
    """I couldn’t agree more with this!""",
    """Just wow. Loving this!""",
    """This is really cool, love it!""",
    """Such a great post, well done!""",
    """This is so relatable, love it!""",
    """Couldn’t have said it better myself!""",
    """Nailed it with this one!""",
    """Absolutely fantastic, great job!""",
    """This really speaks to me!""",
    """Thanks for the inspiration!""",
    """Really enjoyed this, well done!""",
    """This is exactly what I needed today!""",
    """You’ve got a new fan right here!""",
    """This made me smile, thank you!""",
    """So glad I saw this today!""",
    """This is pure gold, seriously!""",
    """Totally agree with this!""",
    """Just had to share this, it’s too good!""",
    """This is spot on, well done!""",
    """Really impressive work here!""",
    """Love the vibe of this post!""",
    """This is incredibly well done!""",
    """Just what I needed to see today!""",
    """This is top-notch content, thank you!""",
    """Exactly what I was thinking, great post!""",
    """So true, I can totally relate!""",
    """This just made my day a lot better!""",
    """Amazing work, keep it up!""",
    """This is something special, well done!""",
    """You really nailed it with this!""",
    """This is going on my list of favorites!""",
    """Can’t get enough of this!""",
    """This is the kind of content I’m here for!""",
    """Wow, just wow. This is great!""",
    """This one really hit home for me!""",
    """Such a solid post, love it!""",
    """This is why I love following you!""",
    """Such a good post, really enjoyed it!""",
    """So glad I didn’t miss this, amazing!""",
    """This is definitely getting a share from me!""",
    """Had to stop and comment, this is great!""",
    """This one really stands out, love it!""",
    """This is seriously good stuff, thanks!""",
    """Just had to say, this is awesome!""",
    """This is definitely one of my favorites!""",
    """This really made me think, great post!""",
    """This is quality content right here!""",
    """Really loving what you’re doing here!""",
    """Had to share this, it’s just too good!""",
    """This post is exactly what I needed today!""",
    """Can’t wait to see more like this!""",
    """You’re killing it with these posts!""",
    """This is just perfect, well done!""",
]
